[package]
name = "differential-topology"
version = "0.1"
path = "src"
lean_version = "master"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5dd341920a487e16af657178ee2ad0e3243168e7"}
