[package]
name = "differential-topology"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "eb20fd059017bda423612b7b19a525f95c4593b4"}
